namespace crgolden.Api
{
    public static class SeedProductCategories
    {
        public static ProductCategory[] ProductCategories => new []
        {
            new ProductCategory(SeedProducts.Products[0].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[1].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[2].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[3].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[4].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[5].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[6].Id, SeedCategories.Categories[2].Id),
            new ProductCategory(SeedProducts.Products[7].Id, SeedCategories.Categories[2].Id),
            new ProductCategory(SeedProducts.Products[8].Id, SeedCategories.Categories[3].Id),
            new ProductCategory(SeedProducts.Products[9].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[10].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[11].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[12].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[13].Id, SeedCategories.Categories[2].Id),
            new ProductCategory(SeedProducts.Products[14].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[15].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[16].Id, SeedCategories.Categories[3].Id),
            new ProductCategory(SeedProducts.Products[17].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[18].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[19].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[20].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[21].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[22].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[23].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[24].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[25].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[26].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[27].Id, SeedCategories.Categories[2].Id),
            new ProductCategory(SeedProducts.Products[28].Id, SeedCategories.Categories[3].Id),
            new ProductCategory(SeedProducts.Products[29].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[30].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[31].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[32].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[33].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[34].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[35].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[36].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[37].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[38].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[39].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[40].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[41].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[42].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[43].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[44].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[45].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[46].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[47].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[48].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[49].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[50].Id, SeedCategories.Categories[2].Id),
            new ProductCategory(SeedProducts.Products[51].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[52].Id, SeedCategories.Categories[3].Id),
            new ProductCategory(SeedProducts.Products[53].Id, SeedCategories.Categories[3].Id),
            new ProductCategory(SeedProducts.Products[54].Id, SeedCategories.Categories[3].Id),
            new ProductCategory(SeedProducts.Products[55].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[56].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[57].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[58].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[59].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[60].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[61].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[62].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[63].Id, SeedCategories.Categories[7].Id),
            new ProductCategory(SeedProducts.Products[64].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[65].Id, SeedCategories.Categories[1].Id),
            new ProductCategory(SeedProducts.Products[66].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[67].Id, SeedCategories.Categories[6].Id),
            new ProductCategory(SeedProducts.Products[68].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[69].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[70].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[71].Id, SeedCategories.Categories[5].Id),
            new ProductCategory(SeedProducts.Products[72].Id, SeedCategories.Categories[4].Id),
            new ProductCategory(SeedProducts.Products[73].Id, SeedCategories.Categories[2].Id),
            new ProductCategory(SeedProducts.Products[74].Id, SeedCategories.Categories[0].Id),
            new ProductCategory(SeedProducts.Products[75].Id, SeedCategories.Categories[0].Id)
        };
    }
}
