namespace Clarity.Api
{
    public static class SeedProductFiles
    {
        public static ProductFile[] ProductFiles => new []
        {
            new ProductFile(SeedProducts.Products[0].Id, SeedFiles.Files[0].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[1].Id, SeedFiles.Files[1].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[2].Id, SeedFiles.Files[2].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[3].Id, SeedFiles.Files[3].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[4].Id, SeedFiles.Files[4].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[5].Id, SeedFiles.Files[5].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[6].Id, SeedFiles.Files[6].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[7].Id, SeedFiles.Files[7].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[8].Id, SeedFiles.Files[8].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[9].Id, SeedFiles.Files[9].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[10].Id, SeedFiles.Files[10].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[11].Id, SeedFiles.Files[11].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[12].Id, SeedFiles.Files[12].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[13].Id, SeedFiles.Files[13].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[14].Id, SeedFiles.Files[14].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[15].Id, SeedFiles.Files[15].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[16].Id, SeedFiles.Files[16].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[17].Id, SeedFiles.Files[17].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[18].Id, SeedFiles.Files[18].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[19].Id, SeedFiles.Files[19].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[20].Id, SeedFiles.Files[20].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[21].Id, SeedFiles.Files[21].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[22].Id, SeedFiles.Files[22].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[23].Id, SeedFiles.Files[23].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[24].Id, SeedFiles.Files[24].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[25].Id, SeedFiles.Files[25].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[26].Id, SeedFiles.Files[26].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[27].Id, SeedFiles.Files[27].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[28].Id, SeedFiles.Files[28].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[29].Id, SeedFiles.Files[29].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[30].Id, SeedFiles.Files[30].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[31].Id, SeedFiles.Files[31].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[32].Id, SeedFiles.Files[32].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[33].Id, SeedFiles.Files[33].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[34].Id, SeedFiles.Files[34].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[35].Id, SeedFiles.Files[35].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[36].Id, SeedFiles.Files[36].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[37].Id, SeedFiles.Files[37].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[38].Id, SeedFiles.Files[38].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[39].Id, SeedFiles.Files[39].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[40].Id, SeedFiles.Files[40].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[41].Id, SeedFiles.Files[41].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[42].Id, SeedFiles.Files[42].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[43].Id, SeedFiles.Files[43].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[44].Id, SeedFiles.Files[44].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[45].Id, SeedFiles.Files[45].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[46].Id, SeedFiles.Files[46].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[47].Id, SeedFiles.Files[47].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[48].Id, SeedFiles.Files[48].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[49].Id, SeedFiles.Files[49].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[50].Id, SeedFiles.Files[50].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[51].Id, SeedFiles.Files[51].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[52].Id, SeedFiles.Files[52].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[53].Id, SeedFiles.Files[53].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[54].Id, SeedFiles.Files[54].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[55].Id, SeedFiles.Files[55].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[56].Id, SeedFiles.Files[56].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[57].Id, SeedFiles.Files[57].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[58].Id, SeedFiles.Files[58].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[59].Id, SeedFiles.Files[59].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[60].Id, SeedFiles.Files[60].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[61].Id, SeedFiles.Files[61].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[62].Id, SeedFiles.Files[62].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[63].Id, SeedFiles.Files[63].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[64].Id, SeedFiles.Files[64].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[65].Id, SeedFiles.Files[65].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[66].Id, SeedFiles.Files[66].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[67].Id, SeedFiles.Files[67].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[68].Id, SeedFiles.Files[68].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[69].Id, SeedFiles.Files[69].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[70].Id, SeedFiles.Files[70].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[71].Id, SeedFiles.Files[71].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[72].Id, SeedFiles.Files[72].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[73].Id, SeedFiles.Files[73].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[74].Id, SeedFiles.Files[74].Id) { IsPrimary = true },
            new ProductFile(SeedProducts.Products[75].Id, SeedFiles.Files[75].Id) { IsPrimary = true }
        };
    }
}
